version: '3.1'

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/24

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234567D_p
      - MYSQL_ROOT_PASSWORD=1234567D_p
      - MYSQL_DATABASE=novus
    volumes:
      - ./deploy/db:/var/lib/mysql
    hostname: db
    networks:
      default:
        ipv4_address: 172.19.0.8